"""Markdown report assembly for a BINNER ``analyze()`` result.

Pure text/formatting; no statistics live here (that's binner_analysis.py) and no
plotting (that's plots.py). ``build_report(R, figs, validation=None)`` returns the
full Markdown string; ``run_analysis.py`` writes it to disk next to the figures.
"""
from __future__ import annotations

import math

import numpy as np
import pandas as pd

import binner_analysis as ba


def _fmt(v, sig=4):
    if v is None:
        return "n/a"
    if isinstance(v, (list, tuple)):
        if len(v) == 2 and all(isinstance(x, (int, float, np.floating)) for x in v):
            return f"[{_fmt(v[0])}, {_fmt(v[1])}]"
        return str(v)
    if isinstance(v, (float, np.floating)):
        if not np.isfinite(v):
            return "n/a"
        return f"{v:.{sig}g}"
    if isinstance(v, bool):
        return "PASS" if v else "FAIL"
    return str(v)


def df_to_md(df: pd.DataFrame, cols=None, rename=None, float_sig=4, index_name=None) -> str:
    """Minimal, dependency-free DataFrame -> GitHub-flavoured Markdown table.

    ``cols`` selects/orders *actual* DataFrame column names (applied after the
    index is turned into a column, so ``index_name`` can appear in it too).
    ``rename`` maps actual column names to display headers; columns not in
    ``rename`` keep their own name as the header. Keeping selection (``cols``)
    and display labels (``rename``) tied to real column names -- instead of a
    free-standing header list -- avoids silently misaligned tables when a
    column is added/removed upstream.
    """
    if df is None or not len(df):
        return "_(no data)_\n"
    d = df.copy()
    if index_name:
        d = d.reset_index().rename(columns={d.index.name or "index": index_name})
    elif d.index.name:
        d = d.reset_index()
    if cols:
        missing = [c for c in cols if c not in d.columns]
        if missing:
            raise KeyError(f"df_to_md: requested cols not present: {missing} (have {list(d.columns)})")
        d = d[cols]
    rename = rename or {}
    hdrs = [rename.get(c, c) for c in d.columns]
    lines = ["| " + " | ".join(str(h) for h in hdrs) + " |",
             "|" + "|".join(["---"] * len(hdrs)) + "|"]
    for _, row in d.iterrows():
        cells = []
        for v in row.values:
            if v is None or (isinstance(v, float) and math.isnan(v)):
                cells.append("n/a")
            elif isinstance(v, (list, tuple, np.ndarray)):
                cells.append(_fmt(list(v), float_sig))
            elif isinstance(v, (float, np.floating)):
                cells.append(_fmt(v, float_sig))
            else:
                cells.append(str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def _section(title, level=2):
    return f"\n{'#' * level} {title}\n"


def _fig(figs, key, caption):
    if key not in figs:
        return ""
    return f"\n![{caption}](figures/{figs[key]})\n\n*{caption}*\n"


# ======================================================================================
def build_report(R: dict, figs: dict, csv_dir: str, validation: dict | None = None) -> str:
    pop = R["pop"]
    N = len(pop.chips)
    model = R["model"]
    out = []
    out.append(f"# BINNER bring-up population report\n")
    out.append(f"Source CSVs: `{csv_dir}` &mdash; {N} chip(s): {', '.join(pop.chips) if N <= 40 else str(N) + ' chips'}\n")
    out.append("Generated by `analysis/run_analysis.py` (BINNER TTGF26d analysis pipeline). "
               "All frequencies are ring/tap oscillation frequencies in MHz unless noted; delays in "
               "ns or ps; process shifts (s_n, s_p, gradients) are dimensionless relative deltas. "
               "Every population estimate reports a 90% two-sided confidence interval, "
               "either a nonparametric chip-level bootstrap (the chip/die is the independent "
               "resampling unit -- rings within a chip are correlated, not independent draws of "
               "the die-to-die process) or, where noted, an exact normal-theory chi-square interval "
               "for a standard deviation.\n")
    if R.get("placement_placeholder"):
        out.append("> **Placement notice:** " + "; ".join(R.get("placement_notes", [])) + "\n")
    if R.get("predictions") is None:
        out.append("> **Predictions notice:** no `--predictions` JSON supplied; predicted-vs-measured "
                   "section is skipped (see docs/VARIATION_MODEL.md; the file is expected to come from "
                   "tools/sdf_predict.py once post-route SDF exists).\n")

    # ---------------- a) ingestion / validation --------------------------------------
    out.append(_section("a. Ingestion, schema validation and completeness"))
    out.append("Screening rules applied (docs/CSV_SCHEMA.md flags; see `binner_analysis.SCREEN_RULES` "
               "for exact thresholds):\n")
    for rid, desc in ba.SCREEN_RULES:
        out.append(f"- **{rid}**: {desc}")
    n_err = sum(1 for i in pop.issues if i["level"] == "ERROR")
    n_warn = sum(1 for i in pop.issues if i["level"] == "WARN")
    out.append(f"\n{len(pop.files)} file(s) read, {n_err} schema ERROR(s), {n_warn} WARNING(s).\n")
    if pop.issues:
        idf = pd.DataFrame(pop.issues)
        out.append(df_to_md(idf.head(40), cols=["chip", "level", "check", "message"]))
        if len(pop.issues) > 40:
            out.append(f"\n_... and {len(pop.issues) - 40} more (see results.json['issues'])._\n")
    out.append(_section("Per-chip completeness", 3))
    out.append(df_to_md(R["completeness"], index_name="chip"))
    if R.get("chip_outliers"):
        out.append("\n**Population outlier screen (R6):** chip(s) with |robust z| > 4 on mean INV ln f: "
                   + ", ".join(f"{c} (z={z:.1f})" for c, z in R["chip_outliers"].items()) + ". "
                   "Kept in yield counts; sigma_d2d is also reported excluding them (see section b).\n")

    # ---------------- b) die-to-die distributions -------------------------------------
    out.append(_section("b. Die-to-die distributions"))
    out.append("Per-chip mean frequency of each structure type, and derived per-stage propagation "
               "delay tpd = 1/(2 * stages * f). Distributions are summarised on ln(f) because process "
               "variation is closer to multiplicative than additive; `rel_sd` below is the 1-sigma "
               "relative (fractional) spread.\n")
    pcm = R["per_chip"]
    show = ["n_inv", "f_inv_mean", "f_nand", "f_nor", "f_fo4", "tpd_inv_ps", "temp_c"]
    out.append(df_to_md(pcm[[c for c in show if c in pcm.columns]].assign(
        f_inv_mean=lambda d: d["f_inv_mean"] / 1e6, f_nand=lambda d: d["f_nand"] / 1e6,
        f_nor=lambda d: d["f_nor"] / 1e6, f_fo4=lambda d: d["f_fo4"] / 1e6
    ).rename(columns={"f_inv_mean": "f_inv_MHz", "f_nand": "f_nand_MHz", "f_nor": "f_nor_MHz",
                      "f_fo4": "f_fo4_MHz"}), index_name="chip"))
    out.append(_fig(figs, "d2d_inv", "INV ring mean frequency: histogram, CDF, normal-probability plot"))
    out.append(_section("Population summary (bootstrap 90% CI)", 3))
    rows = []
    for col, d in R["d2d"].items():
        if "sd" not in d:
            continue
        rows.append({"quantity": d["label"], "n": d["n"], "mean": d["mean"], "sd": d["sd"],
                    "sd_ci90": d.get("sd_ci"), "rel_sd": d.get("rel_sd"), "rel_sd_ci90": d.get("rel_sd_ci"),
                    "shapiro_p": d.get("shapiro_p")})
    out.append(df_to_md(pd.DataFrame(rows)))
    inv = R.get("inv_spread", {})
    if inv:
        out.append(f"\nsigma(ln f_INV) @25C = **{_fmt(inv['sigma_inv_lnf'])}** {_fmt(inv['sigma_inv_ci'])} "
                   f"(90% CI, N={N}); implied sigma_d2d (correcting for rho={_fmt(inv['rho_used'])} "
                   f"between s_n, s_p) = **{_fmt(inv['sigma_d2d_implied'])}** {_fmt(inv['sigma_d2d_implied_ci'])}.\n")
    if R.get("inv_spread_no_outliers"):
        io = R["inv_spread_no_outliers"]
        out.append(f"Excluding the R6 population outlier(s): sigma_d2d implied = "
                   f"**{_fmt(io['sigma_d2d_implied'])}** {_fmt(io['sigma_d2d_implied_ci'])}.\n")

    # ---------------- c) speed bins / GRR ----------------------------------------------
    out.append(_section("c. Speed-bin definitions and gauge R&R"))
    out.append("**Gauge R&R** (repeatability & reproducibility) on the bin metric, following the "
               "standard %GRR / ndc (number of distinct categories) convention: "
               "`sigma_repeat` = pooled within-die sd of the metric across repeat passes, "
               "`sigma_part` = between-die sd corrected for repeatability, "
               "`%GRR = 100*sigma_measurement/sigma_total`, `ndc = 1.41*sigma_part/sigma_measurement` "
               "(floor(ndc) categories can be reliably distinguished; AIAG guidance: ndc >= 5 good, "
               "%GRR < 10% good, 10-30% marginal, > 30% unacceptable).\n")
    grr = R.get("grr_ring")
    if grr:
        out.append(f"**Metric:** {grr['metric']}, {grr['n_chips']} dies x {grr['reps']:.1f} repeat pass(es) avg.\n")
        rows = []
        for tag in ("gauge", "gauge+temp"):
            g = grr[tag]
            rows.append({"component set": tag, "sigma_measurement": g["sigma_ms"], "sigma_part": grr["sigma_part"],
                        "%GRR": g["pct_grr"], "ndc": g["ndc"]})
        out.append(df_to_md(pd.DataFrame(rows)))
        out.append("`gauge` = repeatability alone (same-session repeats); `gauge+temp` additionally folds "
                   "in the temperature-proxy correction uncertainty (a Type-B term invisible to same-session "
                   "repeats, from `temp_coeff_per_C * temp_proxy_sigma_C`).\n")
    gf = R.get("grr_fmax")
    if gf:
        out.append(f"\n**Metric:** {gf['metric']} -- sigma_measurement = max(observed repeat sd, "
                   f"PWM-quantisation floor) = **{_fmt(gf['sigma_ms'])}**; %GRR = {_fmt(gf['pct_grr'])}%, "
                   f"ndc = {gf['ndc']}. Because two repeats of the same tap with the same PWM grid can "
                   "return literally the same reading, `sigma_quant = step/sqrt(12)` floors the estimate; "
                   "the reported sigma_measurement is `max(observed, quant)`.\n")
    for key, title in (("bins_ring", "Bins on mean INV ring frequency"), ("bins_fmax", f"Bins on Fmax ({R.get('bins_fmax', {}).get('tap', '?')})")):
        b = R.get(key)
        if not b:
            continue
        out.append(_section(title, 3))
        out.append(f"f_nom = {b['f_nom'] / 1e6:.3f} MHz; guard band = {b['guard_band_rel'] * 100:.2f}% "
                   "(relative, applied to each bin's lower edge; guard_z x sigma_measurement from the "
                   "GRR above, so misbin risk at a limit is held near 5% one-sided).\n")
        out.append(df_to_md(b["yield"], index_name="bin",
                            cols=["bin", "bin_raw_n", "bin_raw_yield", "bin_raw_ci",
                                  "bin_gb_n", "bin_gb_yield", "bin_gb_ci",
                                  "model_yield_gb", "model_yield_gb_ci"],
                            rename={"bin_raw_n": "n (raw)", "bin_raw_yield": "yield (raw)",
                                    "bin_raw_ci": "CI90 (raw)", "bin_gb_n": "n (GB)",
                                    "bin_gb_yield": "yield (GB)", "bin_gb_ci": "CI90 (GB)",
                                    "model_yield_gb": "model yield (GB)",
                                    "model_yield_gb_ci": "model CI90"}))
        out.append(_fig(figs, key, title))

    # ---------------- d) systematic vs random --------------------------------------
    out.append(_section("d. Systematic (gradient) vs random within-die variance"))
    wd = R.get("within_die", {})
    if wd.get("ok"):
        out.append("Per-chip plane fit `ln f = c - g_x*x - g_y*y + resid` on the 16 identical INV rings "
                   "(placement in normalised tile coordinates; see notice above if placeholder). "
                   "Variance decomposition (REML one-way random-effects model, `y_ij = mu + a_i + e_ij` "
                   "over dies i and rings j):\n")
        vc = wd["var_components"]
        rows = [{"component": k, "sigma (ln f)": math.sqrt(v)} for k, v in vc.items()]
        out.append(df_to_md(pd.DataFrame(rows)))
        out.append(f"\n`sigma_wid` (within-die random mismatch, plane-corrected, R5-screened) = "
                   f"**{_fmt(wd['sigma_wid'])}** {_fmt(wd['sigma_wid_ci'])} (bootstrap 90% CI), "
                   f"pooled over {wd['dof']} residual degrees of freedom; measurement-noise floor "
                   f"sigma_meas = {_fmt(wd['sigma_meas'])}.\n")
        out.append(f"REML (raw ln f, no plane correction): sigma_d2d = {_fmt(wd['reml_raw']['sigma_d2d_lnf'])}, "
                   f"sigma_within_total = {_fmt(wd['reml_raw']['sigma_within_total'])}. "
                   f"REML (plane-corrected): sigma_d2d = {_fmt(wd['reml_plane']['sigma_d2d_lnf'])}, "
                   f"sigma_within_random = {_fmt(wd['reml_plane']['sigma_within_random'])}.\n")
        if wd.get("ring_outliers"):
            out.append(f"\nR5 ring outliers excluded from the gradient/sigma_wid fit: "
                       + "; ".join(f"{c}/{it} (resid={r:.3f})" for c, it, r in wd["ring_outliers"]) + "\n")
        out.append(_section("Per-chip gradient", 3))
        ct = wd["per_chip"]
        out.append(df_to_md(ct[["g_x", "g_y", "g_x_ci", "g_y_ci", "n_rings", "rms_resid"]], index_name="chip"))
        out.append(_fig(figs, "gradient", "Per-die gradient vectors (g_x, g_y)"))
        out.append(_section("Gradient consistency across chips", 3))
        gt = wd["gradient_test"]
        if gt.get("n", 0) >= 3:
            out.append(f"Hotelling T^2 test for a common nonzero mean gradient: "
                       f"mean=({_fmt(gt['mean_gx'])}, {_fmt(gt['mean_gy'])}), T^2={_fmt(gt['hotelling_T2'])}, "
                       f"p={_fmt(gt['p_common'])}. Per-axis test for die-to-die gradient variability beyond "
                       f"per-die fit noise: chi2_gx={_fmt(gt['chi2_g_x'])} (p={_fmt(gt['p_random_g_x'])}), "
                       f"chi2_gy={_fmt(gt['chi2_g_y'])} (p={_fmt(gt['p_random_g_y'])}); "
                       f"tau (excess die-to-die gradient sd) = ({_fmt(gt['tau_g_x'])}, {_fmt(gt['tau_g_y'])}).\n\n"
                       f"**Verdict: {gt['verdict']}.** Minimum common gradient detectable at 80% power, "
                       f"alpha=0.05, N={gt['n']} dies: {_fmt(gt['mde_common'])} per unit coordinate "
                       f"(single-die fit noise sigma = {_fmt(gt['se_single_die'])}).\n")
        else:
            out.append("Fewer than 3 chips with a valid plane fit; gradient-consistency test skipped.\n")
    else:
        out.append("_Insufficient data (need >= 6 valid INV rings on at least one chip)._\n")

    # ---------------- e) N/P skew --------------------------------------------------
    out.append(_section("e. N/P (NMOS/PMOS) skew"))
    npk = R.get("np", {})
    if npk.get("ok"):
        out.append("Per-chip (s_n, s_p) from a weighted/generalised-least-squares fit of "
                   "ln f_k + ln(nominal) + (gradient and temperature corrections) = w_nk*s_n + w_pk*s_p "
                   "over the available structures (INV plane-fit intercept, NAND, NOR, FO4, and "
                   "optionally the delay-chain stage delay). Sensitivities w_n, w_p are model constants "
                   "(overridable via `--model`, e.g. once SDF/SPICE sensitivities exist).\n")
        t = npk["per_chip"]
        out.append(df_to_md(t[["s_n", "s_p", "delta", "sigma_sum", "structures", "temp_used"]],
                            index_name="chip"))
        out.append(_fig(figs, "np_skew", "N/P corner scatter with 90% uncertainty ellipses"))
        out.append(f"\nPopulation sigma_d2d (method-of-moments over s_n, s_p, correcting for average "
                   f"per-chip estimation variance) = **{_fmt(npk['sigma_d2d'])}** {_fmt(npk['sigma_d2d_ci'])}; "
                   f"correlation rho(s_n, s_p) = **{_fmt(npk['rho'])}** {_fmt(npk['rho_ci'])}. "
                   f"Median per-die 1-sigma uncertainty on (s_n - s_p) = {_fmt(npk['median_se_delta'])}, "
                   f"on (s_n + s_p) = {_fmt(npk['median_se_sum'])}.\n")
        out.append("Note: because every structure has w_n + w_p = 1 in the default model, the ratios "
                   "between structures fix `s_n - s_p` tightly but leave `s_n + s_p` resting on the "
                   "absolute frequency -- i.e. on d0 and the temperature correction. Treat `sigma_sum` "
                   "per die with more caution than `delta`.\n")
    else:
        out.append("_Insufficient data (within-die fit unavailable)._\n")

    # ---------------- f) Fmax-vs-tap --------------------------------------------
    out.append(_section("f. Fmax-vs-tap regression"))
    ch = R.get("chain", {})
    out.append("Model: 1/Fmax_k = t_ov + t_mux + n_k*t_stage for tap k with n_k in "
               f"{model['tap_stages']} chain stages (`t_ov` folds the mux constant, i.e. the fitted "
               "intercept `a_fmax = t_ov + t_mux`). Because Fmax is found by PWM-grid binary search, "
               "the true Fmax is only known to lie in an interval [f_pass, f_fail); the primary fit is "
               "an interval-censored Gaussian maximum-likelihood regression (a WLS fit on interval "
               "midpoints is reported alongside as a simpler cross-check). Cross-checked against an "
               "independent linear regression of the DCH0..7 ring half-period vs stage count.\n")
    if "per_chip" in ch and len(ch["per_chip"]):
        t = ch["per_chip"]
        cols = [c for c in ("t_stage", "se_t_stage", "t_ov", "t_stage_dch", "se_t_stage_dch",
                            "t_stage_wls", "monotone", "cens_ok") if c in t.columns]
        out.append(df_to_md((t[cols] * 1e12 if False else t[cols]).assign(
            **{c: t[c] * 1e9 for c in cols if c.startswith(("t_stage", "t_ov")) and t[c].dtype != bool}
        ), index_name="chip"))
        out.append("(t_stage, t_ov, t_stage_dch in ns.)\n")
        out.append(_fig(figs, "fmax_regression", "1/Fmax vs tap stage count (censored fit) and DCH ring cross-check"))
    for pop_key, label in (("pop_t_stage", "t_stage (Fmax fit, ns)"), ("pop_t_ov", "t_ov (ns)"),
                           ("pop_t_stage_dch", "t_stage (DCH ring, ns)")):
        d = ch.get(pop_key)
        if d and "sd" in d:
            out.append(f"\nPopulation {label}: mean = {_fmt(d['mean'] * 1e9)} {_fmt(d['mean_ci'] and [x*1e9 for x in d['mean_ci']])}, "
                       f"sd = {_fmt(d['sd'] * 1e9)} {_fmt(d['sd_ci'] and [x*1e9 for x in d['sd_ci']])} (N={d['n']}).\n")
    cc = ch.get("cross_check")
    if cc:
        out.append(f"\nCross-check t_stage(Fmax) / t_stage(DCH): mean ratio = {_fmt(cc['ratio_mean'])}, "
                   f"sd = {_fmt(cc['ratio_sd'])}, corr = {_fmt(cc['corr'])}. Ratio near 1.0 indicates the "
                   "two independent structures (delay-chain flop path vs free-running DCH ring) agree on "
                   "the per-stage delay.\n")

    # ---------------- g) PUF ---------------------------------------------------
    out.append(_section("g. PUF metrics"))
    p = R.get("puf", {})
    if p.get("ok"):
        n = p["n_chips"]
        out.append(f"N = {n} dies, 16 PUF bits/die from simultaneous paired-ring comparisons "
                   "(docs/CSV_SCHEMA.md Stage 4). Definitions: **uniformity** = mean bit value over all "
                   "bits and dies (ideal 0.5); **inter-chip Hamming distance** = fraction of the 16 bits "
                   "that differ between two dies, averaged over all pairs (ideal 0.5, binomial(16, 0.5)); "
                   "**intra-chip reliability** = 1 - bit-error-rate of repeated reads vs the majority-vote "
                   "reference; **bit aliasing** = P(bit=1) for each bit position across dies (ideal 0.5 "
                   "for every bit; a biased position is less useful for uniqueness); **min-entropy** "
                   "estimated from bit aliasing, `sum_i -log2(max(p_i, 1-p_i))`.\n")
        rows = [
            ("Uniformity (mean bit value)", p["uniformity_mean"], p.get("uniformity_ci"), 0.5),
            ("Inter-chip HD (mean)", p.get("inter_hd_mean"), p.get("inter_hd_chip_boot_ci"), 0.5),
            ("Intra-chip reliability", p.get("reliability"), None, 1.0),
            ("Intra-chip BER (mean)", p.get("intra_ber_mean"), None, 0.0),
            ("Min-entropy (bits, sum of 16)", p.get("min_entropy_bits"), None, 16.0),
            ("Min-entropy per bit", p.get("min_entropy_per_bit"), None, 1.0),
        ]
        out.append(df_to_md(pd.DataFrame(rows, columns=["metric", "value", "90% CI", "ideal"])))
        out.append(f"\nInter-chip HD: naive per-pair binomial CI {_fmt(p.get('inter_hd_naive_ci'))} "
                   f"treats all {p.get('inter_hd_pairs')} pairs as independent (it understates the true "
                   f"uncertainty because they share only {n} dies); the chip-level bootstrap CI "
                   f"{_fmt(p.get('inter_hd_chip_boot_ci'))} is the honest one and should be quoted.\n")
        if p.get("hot_ber_mean") is not None:
            out.append(f"Stage-5 hot re-test intra-chip BER = {_fmt(p['hot_ber_mean'])} "
                       "(reliability at an elevated temperature).\n")
        exp = p.get("expected", {})
        out.append(f"\nModel-expected intra-chip BER upper bound (Gaussian pair-mismatch model, using ring "
                   f"repeatability as an upper bound on measurement noise) = {_fmt(exp.get('intra_ber_upper'))}; "
                   f"{exp.get('note', '')}\n")
        if p.get("fingerprint_mismatch_bits"):
            bad = {c: v for c, v in p["fingerprint_mismatch_bits"].items() if v}
            if bad:
                out.append(f"\nFingerprint-vs-majority-vote mismatch (should be 0): {bad}\n")
        out.append(_fig(figs, "puf", "Bit aliasing and inter-chip Hamming-distance histogram"))
    else:
        out.append("_No Stage 4 PUF data available._\n")

    # ---------------- h) predicted vs measured ---------------------------------
    out.append(_section("h. Predicted vs measured"))
    pc = R.get("pred_cmp")
    if pc is not None and len(pc):
        out.append("Ratio of measured (25 C corrected) to predicted `tt` (nominal-corner) frequency, "
                   "per item, with the predicted `ss..ff` band shown relative to `tt`.\n")
        out.append(df_to_md(pc[["n", "meas_median", "ratio_median", "ratio_ci", "band_lo_rel",
                                "band_hi_rel", "frac_in_band"]], index_name="item"))
        out.append(_fig(figs, "predictions", "Measured/predicted ratio per item vs predicted process band"))
    else:
        out.append("_No `--predictions` JSON supplied (or no overlapping items); section skipped. "
                   "Expected input: `{item: {tt, ss, ff, lo, hi}}` in Hz, e.g. from "
                   "`tools/sdf_predict.py` once post-route SDF exists (docs/VARIATION_MODEL.md)._\n")

    # ---------------- i) limitations --------------------------------------------
    out.append(_section("i. Limitations at small N"))
    for l in R.get("limitations", []):
        out.append(f"- {l}")
    out.append("")

    # ---------------- j) validation -----------------------------------------
    if validation is not None:
        out.append(_section("j. Validation against injected simulation truth"))
        out.append(f"Truth source: synthetic population truth files (`truth_*.json` / "
                   "`population_truth.json`). Targets are the docs/VARIATION_MODEL.md recovery "
                   "targets for N=20; smaller N is expected to miss them (see section i).\n")
        out.append(_section("Population-level parameters", 3))
        out.append(df_to_md(validation["population"],
                            cols=["parameter", "estimate", "ci_lo", "ci_hi", "truth", "truth_sample",
                                  "error", "rel_error", "ci_covers", "target", "pass", "unit"],
                            rename={"truth_sample": "truth (N-sample stat)", "ci_covers": "CI covers truth",
                                    "pass": "pass target"}))
        out.append(_section("Per-chip parameter recovery (summary over dies)", 3))
        out.append(df_to_md(validation["summary"]))
        verdict = validation["verdict"]
        npass = sum(1 for v in verdict.values() if v)
        out.append(f"\n**Overall: {npass}/{len(verdict)} checks PASS against stated targets.**\n")
        for k, v in verdict.items():
            out.append(f"- {'PASS' if v else 'FAIL'}: {k}")
        out.append("")

    return "\n".join(out) + "\n"
